"""PL-KKT-hPINN-style ENFORCE benchmark for the 1D isothermal CSTR.

The goal of this script is *comparability*, not to change ENFORCE itself.
It mirrors the important 1D PL-KKT-hPINN experimental settings:

* 150 data points split into 90 train / 30 validation / 30 test
* a fixed data split generated by NumPy RandomState(42), equivalent to
  sklearn.utils.shuffle(..., random_state=42)
* MaxAbs scaling fitted to the full 150-point data set before splitting
* 2 hidden layers, 32 hidden neurons, 1000 epochs, batch size 16
* learning rate 1e-4, float32, CPU
* test-set batches of 16 (16 + 14 samples)

ENFORCE-specific projection settings used for the cross-method benchmark:
* inference/training tolerance = 1e-6
* maximum projection iterations = 100
* displacement weight = 0.5 (ENFORCE default)

Jobs
----
train:
    Train on the 90 PL-style training rows and save a checkpoint.
experiment:
    Load the saved checkpoint and evaluate only the 30 PL-style test rows.
    Data loading/scaling/splitting occurs before the evaluation timer.  The
    timer itself begins before model construction/loading and ends after
    prediction, metric calculation, and report writing, matching the timing
    boundary used by PL-KKT-hPINN's evaluate_model() as closely as practical.
"""

import os

# ENFORCE 1.0.x chooses CUDA internally whenever CUDA is visible.  Hide CUDA
# before importing torch so every component is guaranteed to use CPU.
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import argparse
import json
import math
import random
import time
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
import torch

from enforce.core.model import ENFORCE, ENFORCEConfig
from enforce.engines.train import Trainer, TrainingConfig


# ---------------------------------------------------------------------------
# Fixed benchmark configuration
# ---------------------------------------------------------------------------

SPLIT_SEED = 42
BASE_MODEL_SEED = 42
VAL_RATIO = 0.20
TEST_RATIO = 0.20

HIDDEN_NEURONS = 32
PL_HIDDEN_LAYERS = 2
# ENFORCE creates one input->hidden layer plus `hidden_layers` additional
# hidden->hidden layers. Therefore hidden_layers=1 gives two actual hidden
# affine/ReLU layers, matching PL-KKT-hPINN hidden_num=2.
ENFORCE_HIDDEN_LAYERS_ARG = PL_HIDDEN_LAYERS - 1
EPOCHS = 1000
BATCH_SIZE = 16
LEARNING_RATE = 1.0e-4
DTYPE = torch.float32
DEVICE = torch.device("cpu")

PROJECTION_TOLERANCE = 1.0e-6
MAX_PROJECTION_ITERATIONS = 100
DISPLACEMENT_WEIGHT = 0.5

# CSTR constants
TAU = 10.0
CBO = 2.0
CCO = 0.0
T_ISO = 350.0
R = 8.314
AFO = 1.0e13
EAF = 90000.0
ARO = 1.0e11
EAR = 80000.0
KF = AFO * math.exp(-EAF / (R * T_ISO))
KR = ARO * math.exp(-EAR / (R * T_ISO))

REQUIRED_COLUMNS = ["Cao", "Ca", "Cb", "Cc"]


# ---------------------------------------------------------------------------
# Data handling: reproduce PL-KKT-hPINN's split + MaxAbs scaling
# ---------------------------------------------------------------------------


def load_and_prepare_data(data_path: Path) -> Dict[str, np.ndarray]:
    """Load, MaxAbs-scale, and split exactly once using the PL-style protocol."""

    if not data_path.exists():
        raise FileNotFoundError(f"Data file not found: {data_path.resolve()}")

    df = pd.read_csv(data_path)
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(
            f"Missing columns {missing}. Expected columns: {REQUIRED_COLUMNS}"
        )

    raw = (
        df[REQUIRED_COLUMNS]
        .dropna()
        .to_numpy(dtype=np.float64, copy=True)
    )
    n = raw.shape[0]
    if n != 150:
        print(
            f"WARNING: PL case study uses 150 rows; this file contains {n}. "
            "The same 60/20/20 logic will still be applied."
        )

    # PL-KKT-hPINN fits MaxAbsScaler on the complete data set before splitting.
    scales = np.max(np.abs(raw), axis=0)
    scales[scales == 0.0] = 1.0
    scaled = raw / scales

    # Equivalent permutation to sklearn.utils.shuffle(..., random_state=42).
    permutation = np.random.RandomState(SPLIT_SEED).permutation(n)

    n_val = int(VAL_RATIO * n)
    n_test = int(TEST_RATIO * n)
    n_train = n - n_val - n_test

    train_idx = permutation[:n_train]
    val_idx = permutation[n_train : n_train + n_val]
    test_idx = permutation[n_train + n_val :]

    return {
        "raw": raw,
        "scaled": scaled,
        "scales": scales,
        "permutation": permutation,
        "train_idx": train_idx,
        "val_idx": val_idx,
        "test_idx": test_idx,
        "x_train_scaled": scaled[train_idx, 0:1],
        "y_train_scaled": scaled[train_idx, 1:4],
        "x_val_scaled": scaled[val_idx, 0:1],
        "y_val_scaled": scaled[val_idx, 1:4],
        "x_test_scaled": scaled[test_idx, 0:1],
        "y_test_scaled": scaled[test_idx, 1:4],
        "x_test_raw": raw[test_idx, 0:1],
        "y_test_raw": raw[test_idx, 1:4],
    }


def save_split_description(prepared: Dict[str, np.ndarray], output_path: Path) -> None:
    rows = []
    for split_name in ("train", "val", "test"):
        for order, source_index in enumerate(prepared[f"{split_name}_idx"]):
            rows.append(
                {
                    "split": split_name,
                    "order_within_split": order,
                    "source_row_index_zero_based": int(source_index),
                }
            )
    pd.DataFrame(rows).to_csv(output_path, index=False)


# ---------------------------------------------------------------------------
# Physical constraints
# ---------------------------------------------------------------------------


def cstr_constraints(x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    """Original nonlinear CSTR equality constraints in physical units."""
    cao = x[:, 0]
    ca = y[:, 0]
    cb = y[:, 1]
    cc = y[:, 2]

    g1 = cao - ca - KF * ca * cb.pow(2) * TAU + KR * cc * TAU
    g2 = cao - ca + CBO - cb + CCO - cc
    return torch.stack((g1, g2), dim=1)


# ---------------------------------------------------------------------------
# Model construction
# ---------------------------------------------------------------------------


def model_seed_for_run(run: int) -> int:
    # Split remains fixed at 42.  Repeated runs vary only model/training RNG.
    return BASE_MODEL_SEED + (run - 1)


def build_model(scales: np.ndarray, run: int) -> ENFORCE:
    """Build ENFORCE with PL-style MaxAbs scaling represented as mean=0/std=scale."""

    model_seed = model_seed_for_run(run)
    torch.manual_seed(model_seed)
    np.random.seed(model_seed)
    random.seed(model_seed)

    # ENFORCE expects affine scaling y_scaled=(y-mean)/std.  Setting mean=0 and
    # std=MaxAbs scale reproduces PL-KKT-hPINN's MaxAbsScaler exactly.
    scaling_input = (
        torch.zeros(1, dtype=DTYPE, device=DEVICE),
        torch.as_tensor(scales[0:1], dtype=DTYPE, device=DEVICE),
    )
    scaling_output = (
        torch.zeros(3, dtype=DTYPE, device=DEVICE),
        torch.as_tensor(scales[1:4], dtype=DTYPE, device=DEVICE),
    )

    config = ENFORCEConfig(
        input_neurons=1,
        output_neurons=3,
        hidden_neurons=HIDDEN_NEURONS,
        hidden_layers=ENFORCE_HIDDEN_LAYERS_ARG,
        training_tolerance=PROJECTION_TOLERANCE,
        inference_tolerance=PROJECTION_TOLERANCE,
        max_it=MAX_PROJECTION_ITERATIONS,
        supervised=True,
        weight_loss_displacement=DISPLACEMENT_WEIGHT,
        epoch_start_hard_constrained=0,
        ada_np_auto_activation=True,
        random_seed=model_seed,
    )

    model = ENFORCE(
        scaling_input=scaling_input,
        scaling_output=scaling_output,
        c=cstr_constraints,
        config=config,
        constrained=True,
        weighting_option=1,
    )

    # ENFORCE 1.0.x stores scaling quantities as ordinary attributes and creates
    # them as float32 internally. Convert *both* network and scaling attributes
    # explicitly so the benchmark really is float32 throughout.
    model = model.to(device=DEVICE, dtype=DTYPE)
    model.device = "cpu"
    model.mean_input = model.mean_input.to(device=DEVICE, dtype=DTYPE)
    model.std_input = model.std_input.to(device=DEVICE, dtype=DTYPE)
    model.mean_output = model.mean_output.to(device=DEVICE, dtype=DTYPE)
    model.std_output = model.std_output.to(device=DEVICE, dtype=DTYPE)
    return model


# ---------------------------------------------------------------------------
# Metrics, including an exact PL-style scaled RMSE/violation aggregation
# ---------------------------------------------------------------------------


def physical_residuals(
    cao: np.ndarray, predictions: np.ndarray
) -> Tuple[np.ndarray, np.ndarray]:
    ca = predictions[:, 0]
    cb = predictions[:, 1]
    cc = predictions[:, 2]
    g1 = cao - ca - KF * ca * cb**2 * TAU + KR * cc * TAU
    g2 = cao - ca + CBO - cb + CCO - cc
    return g1, g2


def batched_slices(n: int, batch_size: int) -> Iterable[slice]:
    for start in range(0, n, batch_size):
        yield slice(start, min(start + batch_size, n))


def compute_metrics(
    y_pred_physical: np.ndarray,
    y_true_physical: np.ndarray,
    x_test_physical: np.ndarray,
    y_output_scales: np.ndarray,
) -> Dict[str, float]:
    y_pred_scaled = y_pred_physical / y_output_scales
    y_true_scaled = y_true_physical / y_output_scales

    # Exact PL-style aggregation: per-batch MSE, unweighted mean over batches,
    # then square root. With 30 test points and batch_size=16 this gives two
    # equally weighted batches (16 and 14), matching PL's evaluation logic.
    batch_mses: List[float] = []
    batch_original_violations: List[float] = []

    all_g1, all_g2 = physical_residuals(
        x_test_physical[:, 0], y_pred_physical
    )
    abs_residuals = np.abs(np.column_stack((all_g1, all_g2)))

    for sl in batched_slices(len(y_pred_physical), BATCH_SIZE):
        batch_mses.append(
            float(np.mean((y_pred_scaled[sl] - y_true_scaled[sl]) ** 2))
        )
        batch_original_violations.append(float(np.mean(abs_residuals[sl])))

    per_output_rmse = np.sqrt(
        np.mean((y_pred_physical - y_true_physical) ** 2, axis=0)
    )

    return {
        "rmse_pl_style_scaled": float(np.sqrt(np.mean(batch_mses))),
        "original_nonlinear_violation_pl_style": float(
            np.mean(batch_original_violations)
        ),
        "rmse_ca_physical": float(per_output_rmse[0]),
        "rmse_cb_physical": float(per_output_rmse[1]),
        "rmse_cc_physical": float(per_output_rmse[2]),
        "rmse_overall_physical": float(
            np.sqrt(np.mean((y_pred_physical - y_true_physical) ** 2))
        ),
        "g1_mean_abs": float(np.mean(np.abs(all_g1))),
        "g2_mean_abs": float(np.mean(np.abs(all_g2))),
        "overall_mean_abs_violation": float(np.mean(abs_residuals)),
        "g1_max_abs": float(np.max(np.abs(all_g1))),
        "g2_max_abs": float(np.max(np.abs(all_g2))),
        "overall_max_abs_violation": float(np.max(abs_residuals)),
    }


def write_report(
    report_path: Path,
    metrics: Dict[str, float],
    projection_iterations: List[int],
) -> None:
    with report_path.open("w", encoding="utf-8") as f:
        f.write("ENFORCE CSTR - PL-KKT-hPINN-style benchmark\n")
        f.write("=" * 58 + "\n")
        f.write(f"projection_tolerance: {PROJECTION_TOLERANCE:.3e}\n")
        f.write(f"max_projection_iterations: {MAX_PROJECTION_ITERATIONS}\n")
        f.write(f"test_batch_size: {BATCH_SIZE}\n")
        f.write(f"projection_iterations_by_batch: {projection_iterations}\n")
        if projection_iterations:
            f.write(
                "mean_projection_iterations_across_batches: "
                f"{np.mean(projection_iterations):.6f}\n"
            )
        f.write("\nMetrics\n")
        for key, value in metrics.items():
            f.write(f"{key}: {value:.12e}\n")


# ---------------------------------------------------------------------------
# Jobs
# ---------------------------------------------------------------------------


def train_job(args: argparse.Namespace, prepared: Dict[str, np.ndarray]) -> None:
    models_dir = Path(args.models_dir)
    results_dir = Path(args.results_dir)
    models_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    model = build_model(prepared["scales"], args.run)

    x_train = torch.as_tensor(
        prepared["x_train_scaled"], dtype=DTYPE, device=DEVICE
    )
    y_train = torch.as_tensor(
        prepared["y_train_scaled"], dtype=DTYPE, device=DEVICE
    )

    print("\nPL-style benchmark configuration")
    print(f"split: train={len(prepared['train_idx'])}, val={len(prepared['val_idx'])}, test={len(prepared['test_idx'])}")
    print(f"network: [1, {HIDDEN_NEURONS}, {HIDDEN_NEURONS}, 3]")
    print(f"ENFORCE hidden_layers argument={ENFORCE_HIDDEN_LAYERS_ARG} (two actual hidden layers)")
    print(f"epochs={EPOCHS}, batch_size={BATCH_SIZE}, learning_rate={LEARNING_RATE}")
    print(f"dtype=float32, device=cpu, model_seed={model_seed_for_run(args.run)}")
    print(f"projection tolerance={PROJECTION_TOLERANCE}, max_it={MAX_PROJECTION_ITERATIONS}")

    training_config = TrainingConfig(
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        learning_rate=LEARNING_RATE,
        random_seed=model_seed_for_run(args.run),
    )
    trainer = Trainer(model=model, config=training_config)
    model = trainer.fit(x_train, y_train)

    checkpoint_path = models_dir / f"enforce_run_{args.run}.pt"
    torch.save(model.state_dict(), checkpoint_path)

    metadata = {
        "run": args.run,
        "model_seed": model_seed_for_run(args.run),
        "split_seed": SPLIT_SEED,
        "columns": REQUIRED_COLUMNS,
        "maxabs_scales": prepared["scales"].tolist(),
        "configuration": {
            "hidden_neurons": HIDDEN_NEURONS,
            "actual_hidden_layers": PL_HIDDEN_LAYERS,
            "enforce_hidden_layers_argument": ENFORCE_HIDDEN_LAYERS_ARG,
            "epochs": EPOCHS,
            "batch_size": BATCH_SIZE,
            "learning_rate": LEARNING_RATE,
            "dtype": "float32",
            "device": "cpu",
            "projection_tolerance": PROJECTION_TOLERANCE,
            "max_projection_iterations": MAX_PROJECTION_ITERATIONS,
            "weight_loss_displacement": DISPLACEMENT_WEIGHT,
            "checkpoint_policy": "final_epoch",
            "validation_used_by_native_trainer": False,
            "test_shuffle": False,
            "train_shuffle": True,
        },
    }
    with (models_dir / f"enforce_run_{args.run}_metadata.json").open(
        "w", encoding="utf-8"
    ) as f:
        json.dump(metadata, f, indent=2)

    save_split_description(prepared, results_dir / "pl_split_indices.csv")
    print(f"Saved checkpoint: {checkpoint_path}")


def experiment_job(args: argparse.Namespace, prepared: Dict[str, np.ndarray]) -> None:
    models_dir = Path(args.models_dir)
    results_dir = Path(args.results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_path = models_dir / f"enforce_run_{args.run}.pt"
    if not checkpoint_path.exists():
        raise FileNotFoundError(
            f"Checkpoint not found: {checkpoint_path}. Run --job train first."
        )

    # IMPORTANT: all data loading/scaling/split work above is intentionally
    # outside the timer, just as PL-KKT-hPINN calls LoadData before eval_start.
    x_test_scaled = prepared["x_test_scaled"]
    y_test_raw = prepared["y_test_raw"]
    x_test_raw = prepared["x_test_raw"]
    output_scales = prepared["scales"][1:4]

    eval_start = time.perf_counter()

    # Model construction + loading are inside the timer, matching PL's
    # evaluate_model() timing boundary.
    model = build_model(prepared["scales"], args.run)
    state_dict = torch.load(checkpoint_path, map_location=DEVICE)
    model.load_state_dict(state_dict)
    model.eval()

    predictions_physical: List[np.ndarray] = []
    projection_iterations: List[int] = []

    # ENFORCE cannot use torch.no_grad(): it needs autograd to compute dc/dy.
    for sl in batched_slices(len(x_test_scaled), BATCH_SIZE):
        xb = torch.as_tensor(x_test_scaled[sl], dtype=DTYPE, device=DEVICE)
        with torch.enable_grad():
            ytilde_scaled, _yhat_scaled, proj_iter = model.predict(
                xb, training=False
            )
            _, ytilde_physical = model.unscale(xb, ytilde_scaled)
        predictions_physical.append(
            ytilde_physical.detach().cpu().numpy().astype(np.float64)
        )
        projection_iterations.append(int(proj_iter))

    y_pred_physical = np.concatenate(predictions_physical, axis=0)
    metrics = compute_metrics(
        y_pred_physical=y_pred_physical,
        y_true_physical=y_test_raw,
        x_test_physical=x_test_raw,
        y_output_scales=output_scales,
    )

    g1, g2 = physical_residuals(x_test_raw[:, 0], y_pred_physical)
    prediction_path = results_dir / f"enforce_run_{args.run}_test_predictions.csv"
    

    report_path = results_dir / f"enforce_run_{args.run}_report.txt"
    write_report(report_path, metrics, projection_iterations)

    # PL's evaluate_model writes its report before the outer timer stops, so we
    # also stop only after prediction/metrics/report output are complete.
    evaluation_time = time.perf_counter() - eval_start
    
    pd.DataFrame(
        {
            "source_row_index_zero_based": prepared["test_idx"],
            "Cao": x_test_raw[:, 0],
            "Ca_true": y_test_raw[:, 0],
            "Cb_true": y_test_raw[:, 1],
            "Cc_true": y_test_raw[:, 2],
            "Ca_pred": y_pred_physical[:, 0],
            "Cb_pred": y_pred_physical[:, 1],
            "Cc_pred": y_pred_physical[:, 2],
            "g1": g1,
            "g2": g2,
            "abs_g1": np.abs(g1),
            "abs_g2": np.abs(g2),
        }
    ).to_csv(prediction_path, index=False)
    
    

    metrics_path = results_dir / f"enforce_run_{args.run}_metrics.json"
    metrics_payload = {
        **metrics,
        "run": args.run,
        "projection_iterations_by_batch": projection_iterations,
        "mean_projection_iterations_across_batches": float(
            np.mean(projection_iterations)
        ),
        "evaluation_time_sec": evaluation_time,
    }
    with metrics_path.open("w", encoding="utf-8") as f:
        json.dump(metrics_payload, f, indent=2)

    print("\n========== ENFORCE PL-STYLE TEST RESULTS ==========")
    print(f"Scaled RMSE (PL-style): {metrics['rmse_pl_style_scaled']:.10e}")
    print(
        "Original nonlinear violation (PL-style): "
        f"{metrics['original_nonlinear_violation_pl_style']:.10e}"
    )
    print(f"Physical overall RMSE: {metrics['rmse_overall_physical']:.10e}")
    print(f"mean |g1|: {metrics['g1_mean_abs']:.10e}")
    print(f"mean |g2|: {metrics['g2_mean_abs']:.10e}")
    print(
        "overall mean |g|: "
        f"{metrics['overall_mean_abs_violation']:.10e}"
    )
    print(
        "overall max |g|:  "
        f"{metrics['overall_max_abs_violation']:.10e}"
    )
    print(f"Projection iterations by test batch: {projection_iterations}")
    print(f"Evaluation time: {evaluation_time:.6f} s")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--job", choices=["train", "experiment"], required=True)
    p.add_argument("--data", default="data.csv")
    p.add_argument("--run", type=int, default=1)
    p.add_argument("--models-dir", default="models")
    p.add_argument("--results-dir", default="results")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if args.run < 1:
        raise ValueError("--run must be >= 1")

    # Match PL's float64 CPU setup.
    torch.set_default_dtype(torch.float32)
    prepared = load_and_prepare_data(Path(args.data))

    if args.job == "train":
        train_job(args, prepared)
    else:
        experiment_job(args, prepared)


if __name__ == "__main__":
    main()
